spring.application.name=backend-infra-ti

# Origen del front permitido por CORS (usado en @CrossOrigin de los controllers)
app.cors.origen-front=http://localhost:4200

# Deshabilitado hasta integrar la base de datos
spring.autoconfigure.exclude=\
  org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration,\
  org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration
